---
title: "Global Fusarium graminearum Database"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style2.css
    social: menu
---



```{r setup, include=FALSE}

library(flexdashboard)
library(readxl)
library(tidyverse)
library(crosstalk)
library(plotly)
library(viridis)
```



```{r load data, include=FALSE}
Sys.setlocale("LC_ALL", 'pt_BR.UTF-8')
# carrega os dados com lat e long

  
#read_excel_allsheets <- function(filename) {
#    sheets <- readxl::excel_sheets(filename)
#    x <-    lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
#    names(x) <- sheets
#    x
#}

#fgsc<- read_excel_allsheets("fgsc-dat2.xlsx")
#fgsc$`Machado et al 2015`
#rbind(fgsc$`Machado et al 2015`, fgsc$`Machado et al 2017`)
s1 <- read_excel("fgsc-dat4.xlsx", 1)
s2 <- read_excel("fgsc-dat4.xlsx", 2)
s3 <- read_excel("fgsc-dat4.xlsx", 3)
s4 <- read_excel("fgsc-dat4.xlsx", 4)
s5 <- read_excel("fgsc-dat4.xlsx", 5)
s6 <- read_excel("fgsc-dat4.xlsx", 6)
s7 <- read_excel("fgsc-dat4.xlsx", 7)
s8 <- read_excel("fgsc-dat4.xlsx", 8)
s9 <- read_excel("fgsc-dat4.xlsx", 9)
s10 <- read_excel("fgsc-dat4.xlsx", 10)
s11 <- read_excel("fgsc-dat4.xlsx", 11)
s12 <- read_excel("fgsc-dat4.xlsx", 12)
s13 <- read_excel("fgsc-dat4.xlsx", 13)
s14 <- read_excel("fgsc-dat4.xlsx", 14)
s15 <- read_excel("fgsc-dat4.xlsx", 15)
s16 <- read_excel("fgsc-dat4.xlsx", 16)

s19 <- read_excel("fgsc-dat4.xlsx", 19)
s20 <- read_excel("fgsc-dat4.xlsx", 20)
s21 <- read_excel("fgsc-dat4.xlsx", 21)
s22 <- read_excel("fgsc-dat4.xlsx", 22)

s23 <- read_excel("fgsc-dat4.xlsx", 23)
s24 <- read_excel("fgsc-dat4.xlsx", 24)
s25 <- read_excel("fgsc-dat4.xlsx", 25)
s26 <- read_excel("fgsc-dat4.xlsx", 26)
s27 <- read_excel("fgsc-dat4.xlsx", 27)
s28 <- read_excel("fgsc-dat4.xlsx", 28)

s29 <- read_excel("fgsc-dat4.xlsx", 29)

s30 <- read_excel("fgsc-dat4.xlsx", 30)
s31 <- read_excel("fgsc-dat4.xlsx", 31)
s32 <- read_excel("fgsc-dat4.xlsx", 32)
s33 <- read_excel("fgsc-dat4.xlsx", 33)
s34 <- read_excel("fgsc-dat4.xlsx", 34)
s35 <- read_excel("fgsc-dat4.xlsx", 35)
s36 <- read_excel("fgsc-dat4.xlsx", 36)
s37 <- read_excel("fgsc-dat4.xlsx", 37)
s38 <- read_excel("fgsc-dat4.xlsx", 38)
fgsc2 <- rbind(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s19, s20, s21, s22, s23, s24, s25, s26, s27, s28, s29, s30, s31, s32, s33, s34, s35, s36, s37, s38)
fgsc2$Latitude <- round(jitter(fgsc2$Latitude, factor = 6),4)
fgsc2$Longitude <- round(jitter(fgsc2$Longitude, factor = 6),4)

fgsc <- fgsc2 %>% select(c(13,2,6,7, 8,9, 10, 14, 19, 20, 21))
library(plyr)
table(fgsc$FGSC)
fgsc$FGSC2 <- revalue(fgsc$FGSC, 
                     c("F. graminearum" = "Fgra",
                            "F. meridionale" = "Fmer",
                              "F. cortaderiae" = "Fcor",
                                  "F. austroamericanum" = "Faus",
                                  "F. asiaticum" = "Fasi", 
                                  "F. louisianense" = "Flou", 
                                  "F. boothii" = "Fboo",
                                  "F. gerlachii" = "Fger", 
                                  "F. ussurianum" = "Fuss",
                                  "F. vorosii" = "Fvor", 
                       "F. acaciae-mearnsii" = "Faca", 
                       "F. boothii X F. graminearum hybrid" = "Fboo x Fgra",
                       "F. brasilicum" = "Fbra",
                       "F. aethiopicum" = "Faet"
                       
                                  ))
fgsc$Year <- as.numeric(fgsc$Year)
fgsc <- fgsc %>% 
  filter(FGSC != 30) %>% 
  filter(FGSC != "F. cerealis") %>% 
  filter(FGSC != "F. culmorum") 

fgsc$Host <- revalue(fgsc$Host, 
                     c("oat" = "Oat",
                       "corn" = "Maize",
                       "wheat" = "Wheat", 
                     "barley" = "Barley"))

fgsc$Tri_genotype <- revalue(fgsc$Tri_genotype, 
                     c("NX2" = "NX-2"))
```



```{r all table, echo=FALSE}
library(crosstalk)
library(leaflet)
library(DT)
sd <- SharedData$new(fgsc)
sd2 <- SharedData$new(fgsc2)
```

<i class="fa fa-home" aria-hidden="true"></i> Main dashboard
==================


Column {}
----------------------------------


### Filters
<table class= "table">
<tr>
<td width=33%>
The **FGSC database** is a curated database of peer-reviewed information of *F. graminearum* species complex (FGSC) members strains. Apply the filters to update the table, plot and map. Backspace to clean up your search.  
Last update: `r Sys.Date()`  
<input type="button" value="Clean all filters" onClick="window.location.reload()">


</td><td>
```{r}
filter_select("Pub1", "Select article(s)", sd, ~Pub1)
filter_select("Country", "Select Country", sd, ~Country)
filter_slider("Year", "Year of isolation", sd, ~Year)
```
</td><td>
```{r}
filter_select("Host", "Host", sd, ~Host)
filter_select("FGSC", "Species", sd, ~FGSC)
filter_select("Tri_genotype", "Select genotype(s)", sd, ~Tri_genotype)
```
</td></tr></table>





### <i aria-hidden="true"></i> Table




```{r}
datatable(sd, 
          extensions = c('Buttons', 'ColReorder'),
          escape = TRUE,
          rownames = FALSE, 
          colnames = c('Code', 'Host', 'Country', 'Year', 'Lat', 'Long', 'FGSC2', 'Tri genotype', 'Pub1'), 
         class = 'cell-border stripe',
                      options=list(dom = 'Bfrtip',
                                   buttons = c( 'excel', 'pdf'), deferRender=TRUE, 
                         scrollY='520px', 
                         scroller=TRUE,
                          colReorder = F,
                         
  pageLength = 50,
    fontSize = 8,
  lengthMenu = c(100, 250, 500))) %>% 
 formatStyle(
  c('Collection code', 'Host', 'Country', 'Year', 'Latitude', 'Longitude', 'FGSC', 'Tri_genotype', 'Pub1'),
  fontSize = '90%')
```



Column {}
----------------------------------

###  <i class="fa fa-map" aria-hidden="true"></i> Geographic map

```{r}
library(viridis)
library(leaflet)
pal <- colorFactor("viridis", domain = c("15-ADON", "3-ADON", "DON", "DON/NIV", "NIV", "NX-2"))

library(magrittr)
leaflet(sd) %>% 
  addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=r&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = 'Google') %>% 
  
  addCircleMarkers(group = "Species", color = NA, fillColor = ~pal(Tri_genotype), radius = 5, fillOpacity = 0.9, label = ~FGSC) %>% 
addLegend("bottomleft", pal = pal, values = ~Tri_genotype, title = "Tri genotype",  opacity = 1) %>%  
  
addEasyButton(easyButton(
    icon="fa-globe", title="Back to initial view",
    onClick=JS("function(btn, map){ map.setZoom(1); }"))) 

```




### <i class="fa fa-bar-chart" aria-hidden="true"></i> Trichothecene genotype by species frequency plot


```{r}

#fgsc$FGSC2 <- with(fgsc, reorder(FGSC, FGSC, function(x) length(x)))
#p<-sd %>% 
# ggplot(aes(FGSC))+
# geom_bar(aes(fill = Tri_genotype)) +
# theme_grey() +
# scale_fill_viridis(discrete = TRUE)+
# coord_flip()+
# theme(legend.position = "bottom", panel.background = element_rect(fill = "grey97"))+
# labs(fill = "Tri genotype", y = "Frequency", x = "", title = "")
#(gg <- ggplotly(p))


sd %>% 
  plot_ly(x = ~FGSC, 
         color=~Tri_genotype,
      
          colors = viridis_pal(option = "D")(3)) %>% 
  layout(barmode = 'stack',
         margin=list(l=40,r=40,t=40,b=120))

 #add_trace(x = ~FGSC)


```







<i class="fa fa-map" aria-hidden="true"></i> Map and chart
============



Column {data-width=230}
----------------------------------

### Quick filter


```{r}
filter_slider("Year", "Year of isolation", sd, ~Year)
filter_select("Pub1", "Select article(s)", sd, ~Pub1)
filter_select("Country", "Select Country", sd, ~Country)
filter_select("Host", "Host", sd, ~Host)
filter_select("FGSC", "Species", sd, ~FGSC)
filter_select("Tri_genotype", "Select genotype(s)", sd, ~Tri_genotype)
```


<input type="button" value="Clean all filters" onClick="window.location.reload()">



Column {.tabset}
----------------------------------



### <i class="fa fa-map" aria-hidden="true"></i> Tri genotype map


```{r}

library(htmltools)
pal <- colorFactor("viridis", domain = c("15-ADON", "3-ADON", "NIV", "NX-2"))
leaflet(data = sd) %>%
addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=r&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = 'Google') %>% 
    addCircleMarkers(group = "Tri_genotype", radius = 7, fillOpacity = 0.8,  weight=1, color = NA, fillColor = ~pal(Tri_genotype), label = ~FGSC) %>%
addLegend("bottomleft", pal = pal, values = ~Tri_genotype, title = "Tri genotype",  opacity = 1 ) %>%   
 addEasyButton(easyButton(
    icon="fa-globe", title="Back to initial view",
    onClick=JS("function(btn, map){ map.setZoom(2); }"))) 


```

### <i class="fa fa-map" aria-hidden="true"></i> Species map


```{r}

library(htmltools)
pal <- colorFactor("viridis", domain = c(
  "F. graminearum",
"F. meridionale" ,
                              "F. cortaderiae" ,
                                  "F. austroamericanum",
                                  "F. asiaticum", 
                                  "F. louisianense", 
                                  "F. boothii",
                                  "F. gerlachii", 
                                  "F. ussurianum",
                                  "F. vorosii", 
                       "F. acaciae-mearnsii", 
                       "F. boothii X F. graminearum hybrid",
                       "F. brasilicum",
                       "F. aethiopicum"))
leaflet(data = sd) %>%
addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=r&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = 'Google') %>% 
    addCircleMarkers(group = "Tri_genotype", radius = 7, fillOpacity = 0.8,  weight=1, color = NA, fillColor = ~pal(FGSC), label = ~Tri_genotype) %>%
addLegend("bottomleft", pal = pal, values = ~FGSC, title = "Tri genotype",  opacity = 1 ) %>%
 addEasyButton(easyButton(
    icon="fa-globe", title="Back to initial view",
    onClick=JS("function(btn, map){ map.setZoom(2); }"))) 


```



### <i class="fa fa-bar-chart" aria-hidden="true"></i> Tri genotype by species 


```{r}

#fgsc$FGSC2 <- with(fgsc, reorder(FGSC, FGSC, function(x) length(x)))
#p<-sd %>% 
# ggplot(aes(FGSC))+
# geom_bar(aes(fill = Tri_genotype)) +
# theme_grey() +
# scale_fill_viridis(discrete = TRUE)+
# coord_flip()+
# theme(legend.position = "bottom", panel.background = element_rect(fill = "grey97"))+
# labs(fill = "Tri genotype", y = "Frequency", x = "", title = "")
#(gg <- ggplotly(p))


sd %>% 
  plot_ly(x = ~FGSC, 
         color=~Tri_genotype,
      
          colors = viridis_pal(option = "D")(3)) %>% 
  layout(barmode = 'stack',
         margin=list(l=40,r=40,t=40,b=40))

 #add_trace(x = ~FGSC)


```




### <i class="fa fa-bar-chart" aria-hidden="true"></i> Tri genotypes by year


```{r}

#fgsc$FGSC2 <- with(fgsc, reorder(FGSC, FGSC, function(x) length(x)))
#p<-sd %>% 
# ggplot(aes(FGSC))+
# geom_bar(aes(fill = Tri_genotype)) +
# theme_grey() +
# scale_fill_viridis(discrete = TRUE)+
# coord_flip()+
# theme(legend.position = "bottom", panel.background = element_rect(fill = "grey97"))+
# labs(fill = "Tri genotype", y = "Frequency", x = "", title = "")
#(gg <- ggplotly(p))


sd %>% 
  plot_ly(x = ~Year, 
         color=~Tri_genotype,
      
          colors = viridis_pal(option = "D")(3)) %>% 
  layout(barmode = 'stack',
         margin=list(l=40,r=40,t=40,b=40))

 #add_trace(x = ~FGSC)


```



### <i class="fa fa-bar-chart" aria-hidden="true"></i> Tri genotypes by country


```{r}

#fgsc$FGSC2 <- with(fgsc, reorder(FGSC, FGSC, function(x) length(x)))
#p<-sd %>% 
# ggplot(aes(FGSC))+
# geom_bar(aes(fill = Tri_genotype)) +
# theme_grey() +
# scale_fill_viridis(discrete = TRUE)+
# coord_flip()+
# theme(legend.position = "bottom", panel.background = element_rect(fill = "grey97"))+
# labs(fill = "Tri genotype", y = "Frequency", x = "", title = "")
#(gg <- ggplotly(p))


sd %>% 
  plot_ly(x = ~Country, 
         color=~Tri_genotype,
      
          colors = viridis_pal(option = "D")(3)) %>% 
  layout(barmode = 'stack',
         margin=list(l=40,r=40,t=40,b=40))

 #add_trace(x = ~FGSC)


```








<i class="fa fa-table" aria-hidden="true"></i> Full Table
=================

```{r}
datatable(fgsc2, 
          extensions = c('Buttons', 'ColReorder'),
          escape = TRUE, rownames = FALSE,
         class = 'cell-border stripe',
                      options=list(dom = 'Bfrtip',buttons = c( 'excel', 'pdf'),deferRender=TRUE, 
                          scrollY=500, 
                          scroller=TRUE,
                          colReorder = TRUE,
  pageLength = 100,
    fontSize = 8,
  lengthMenu = c(100, 250, 500))) %>% 
formatStyle(c(1:19),
  fontSize = '90%')
```


About the database 
============


Column {.tabset}
----------------------------------

### About

### References


