---
title: ""
author: ""
date: ""
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    css: style.css
---



**Global analysis and online database of the *Fusarium graminearum* species complex members and chemotypes**


**Preliminary list of authors**

Emerson M. Del Ponte, Gláucia M. Moreira  
Departamento de Fitopatologia, Universidade Federal de Viçosa, Viçosa MG Brazil 

Todd J. Ward  
Cees Waalwijk  
Sebastian A. Steinglen  
Dinorah Pan  
Silvana Vero  
Zhang Hao  
Sofia N. Chulze  
Dauri J. Tessmann  
Antonio Moretti 


## Abstract


Key words  



## Introduction


The surge of the *F. graminearum* species complex 

Trichothecene genotypes

Methods for accurate ID of species and genotypes

Surveys across the continents 

Similar databases 


Objectives

- Conduct a systematic review of the literature reporting accurate ID of FGSC members
- Collect ID and metadata, including geography, at the strain level
- Summarize global distribution of species and trichothecene genotypes
- Describe an online database for searching and visualizing FGSC data


## Material and Methods

## Results

## Discussion

## References


