---
title: ""
author: ""
date: ""
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    css: style.css
---


# Introduction

This website aims to provide access to the raw data, the reproducible `R` codes and a resulting manuscript reporting a global analysis and database of strains of the *Fusarium graminearum* species complex (FGSC) which were identifed to species and chemotypes published the peer-review literature. The strain data were obtained directly from the authors of primary research. Details on the data can be found in the `data` webpage.

The data and the analysis reported here will be reported in a manuscript to be submitted to a scientific journal. However, after the manuscript is published somewhere, the document will be update as more strains and peer-reviewed articles are included in the database. An interface for consulting the current FGSC global database can be found at: https://emdelponte.github.io/FGSC


# Credits

Under construction


